

export const GET_WEIGHTS = 'GET_WEIGHTS';
export const UPDATE_STOCK = 'UPDATE_STOCK';

export const CREATE_WEIGHT_REQUEST = 'CREATE_WEIGHT_REQUEST';
export const CREATE_WEIGHT_SUCCESS = 'CREATE_WEIGHT_SUCCESS';
export const CREATE_WEIGHT_FAILURE = 'CREATE_WEIGHT_FAILURE';

export const CREATE_WEIGHT_CATEGORY_REQUEST = 'CREATE_WEIGHT_CATEGORY_REQUEST';
export const CREATE_WEIGHT_CATEGORY_SUCCESS = 'CREATE_WEIGHT_CATEGORY_SUCCESS';
export const CREATE_WEIGHT_CATEGORY_FAILURE = 'CREATE_WEIGHT_CATEGORY_FAILURE';

export const GET_WEIGHT_CATEGORY_REQUEST = 'GET_WEIGHT_CATEGORY_REQUEST';
export const GET_WEIGHT_CATEGORY_SUCCESS = 'GET_WEIGHT_CATEGORY_SUCCESS';
export const GET_WEIGHT_CATEGORY_FAILURE = 'GET_WEIGHT_CATEGORY_FAILURE';
