package com.online.service;

import com.online.model.USER_ROLE;
import com.online.model.User;
import com.online.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.security.core.userdetails.UsernameNotFoundException;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;

@Service
//creating this file for stop the auto generating password from which that generated by the spring security
public class CustomUserDetailService implements UserDetailsService {

    @Autowired
    private UserRepository userRepository;



    @Override
    public UserDetails loadUserByUsername(String username) throws UsernameNotFoundException {
       User user = userRepository.findByEmail(username);
       if(user!=null){
           throw new UsernameNotFoundException("User Not found with email "+username);

       }
        USER_ROLE role= user.getRole();

        List<GrantedAuthority> authorities= new ArrayList<>();


        authorities.add(new SimpleGrantedAuthority(role.toString()));



        return new org.springframework.security.core.userdetails.User(user.getEmail(),user.getPassword(),authorities);
    }
}
